### ISSUE TITLE
1.2.3 Conduct initial stakeholder meeting

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#15]
- [x] Coordinate a Face-to-Face meeting with the Client
- [x] Confirm availability of all participants for the selected date and time

------------

# Questions to ask:

> **Questions are sorting by highest priority first, to lowest priority.**

### How does the management hierarchy look like?

> The current assumption is that, Chiefs will manage site leaders' workload, while site leaders will manage staff's workload. (Does that mean chiefs will manage another chief's workload? or who will manage the chief's workload?)

###  Can you elaborate on how employees currently communicate their availability and preferences for workload assignments?

~~### How easy does the client want the management website to be? Extremely easy to use, w.o any instructions needed, or many functionalities, but there's instructions in them at the beginning on how to use~~
~~- ^ i think that is standard to have, basic instructions on how to use the website~~

### Are there any specific criteria or considerations that managers use when assigning jobs to employees?
> How will managers decide on the job preference of employees? (e.g lets say both officers A and B are available on the same day and would like to work at the small site. who would the manager pick in this case?)
>  Similar to the question before^, how exactly does the manager select which officer to put at which site?

### What types of jobs are there then? what are the diff job preferences that can be chosen?
>"Staff can indicate their job preference for the week". What type of jobs are assigned? can give examples? be specific and general/broad
> What type of skills are required for each roles, any specifics?

~~### Are there any specific criteria or constraints that should be considered during job assignment? (e.g., skills required, preferred shifts, proximity to site)~~

### How many users are expected to be able to access the site concurrently?

~~### What should be the expected response time of the website?~~

**Comment by wqyeo** [comment]
The questions have been derived from issue #9.

Edited to include some questions from #13 . Feel free to add more...

Ideally, it would be best to ask questions that are hard to get definitions or quantitative data out of.

> Ie. Questions, whose answers isn't just a simple definition or quantitative data.

**Comment by kazoohaa** [comment]
Details said by the client:

JTC

modularization & must be self-contained work (everybody do their own thing), gather all the elements and conceptualize all the self-contained functional and non-functional activities
maintenance fee 20-30%
needs cost for building software
simplicity is key
process should not be changed by the software
scalability
user controlled reports

key things: see workload and adjust accordingly, see resources we have (dont want to be over or under staffed), full time and part time guards, standby guards, preference over locations and timing, indicate availability and preference 
heirarchy: chief (planner), site leader (every security site's leader), officers (guards)
*manager (chiefs) assigns leaders
current system: manual with excel sheets add inside names and availabilities (like timetable)
new system total hours should be visible, lowest and highest workload should show up, still need excel to write some macros to show the program

how will they get notified (timetable): one week before they will be able to see already, actual one will come out on Monday so that manager can anticipate whats happening, make the availability a variable, not a hard-coded thing that can be fine-tuned and changed along the way (a specific number of days before it should appear on the system)

should have contingency plan: make reserved list to make sure if someone doesnt show up on the day they state, there is a backup

task allocation criteria: preference: for locations and timing, weekends/weekdays, fixed shift

what are the job preferences they can select?: sentry and walk around guards

UI: manager goes in -> oversight of landing page and able to plan (but this is not UI)

staff availability report: should highlight top 3 staff with lowest workload

no privacy policies yet, focus on key functionalities, interpret the site table properly 

task allocation/workload: not a scheduling AI project, can be 100% manual, should allow manager to come in and reassign work last minute (availability)

how many managers are expected to use the system?: 1 manager and 1 assistant manager

**Comment by Zhwee** [comment]
Summary:
Compiled a list of various questions to ask the client during our live interview, which took place on September 7, 2023. However, it's important to note that only some of the questions have been addressed by the client thus far. The client's response can be found within issue #20. Notes is taken by: @ivriahtyx, @kazoohaa, @Zhwee.

Duration: 2 days
Start/end: 4/9/23 to 5/9/23
