### ISSUE TITLE
3.2.1 Develop a black-box test plan based on requirements

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#56]

**Comment by ivriahtyx** [comment]
Tasks: 

- [x] Define test scenarios based on each requirements
- [x] Evaluate how system handles errors and unexpected inputs

Goals: Identify and document down test case scenarios for all requirements
Completion Criteria: Ensure that test cases are documented so that it can be executed later on. 
Allocated Time: 2 days
Start & End date : 9/11/23 - 10/11/23
